apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
        - name: gcp
          secret:
            items:
              - key: SERVICE_ACCOUNT_JSON
                path: sa.json
            secretName: gcp
      containers:
        - name: api
          image: "{{ .Values.image }}"
          command:
            - poetry
            - run
            - uvicorn
            - misfortune.api:app
            - --host
            - 0.0.0.0
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - mountPath: /secret
              name: gcp
          envFrom:
            - secretRef:
                name: gcp
            - secretRef:
                name: tokens
          livenessProbe:
            httpGet:
              port: http
              path: /probe/live
