---
apiVersion: v1
kind: Service
metadata:
  name: bot
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bot
spec:
  replicas: 1
  serviceName: bot
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: "{{ .Values.image }}"
          command:
            - poetry
            - run
            - misfortune.bot
          env:
            - name: API_URL
              value: http://api
          envFrom:
            - secretRef:
                name: tokens
