apiVersion: v1
kind: Secret
metadata:
  name: tokens
stringData:
  TELEGRAM_TOKEN: "{{ .Values.secret.telegramToken }}"
  INTERNAL_TOKEN: "{{ .Values.secret.internalToken }}"
data:
  WHEEL_TOKEN: "{{ .Values.secret.wheelToken }}"
